# Use a base image with glibc-2.27
FROM debian:buster

WORKDIR /app

# Copy your coredump and its dependencies into the container
COPY . /app


# Run your application (replace "your_app_executable" with the actual name of your coredump executable)
CMD ["bash"]

